## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker build -t reverseproxy ./reverseproxy
## Tagging
  - docker tag udagram-api-feed nhanhx/udagram-api-feed:v1
  - docker tag udagram-api-user nhanhx/udagram-api-user:v1
  - docker tag udagram-api-frontend nhanhx/udagram-api-frontend:v1
  - docker tag reverseproxy nhanhx/reverseproxy:v1
```bash
## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nhanhx/udagram-api-feed:v1
  - docker push nhanhx/udagram-api-user:v1
  - docker push nhanhx/udagram-api-frontend:v1
  - docker push nhanhx/reverseproxy:v1